version: '3'
services:

  #citizen-microservice
  citizen-microservice:
    build: ./Backend-citizenRegister
    ports: 
      - 5000:5000

  #file-microservice
  file-microservice:
    build: ./Backend-uploadfiles/api-upload
    ports: 
      - 5001:5000


   